version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    env_file:
      - .env

  wordpress:
    depends_on:
      - db
    image: wordpress:4.6.0
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    env_file:
      - .env
    volumes:
      - ./wp-content/themes/shapely:/var/www/html/wp-content/themes/shapely

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6.4-1
    links:
      - db
    ports:
      - "8001:80"
